return {
	-- Main groups
	["SCPF"] = 32667044, -- Foundation Personnel
	["MAD"] = 34020753, -- Manufacturing Department
	["CSO"] = 35684772, -- Community Safety Office

	-- Hostile GOIs
	["AR"] = 35652096, -- Mesmyrize's Anderson's Robotics (Primary)
	["AR>CS"] = 34350021, -- Mesmyrize's AR > Corporate Security 
	["AR>ALD"] = 1067397747, -- Mesmyrize's AR > Advanced Logic Division 
	
	-----------

	["GOC"] = 34202439, -- Mesmyrize's Global Occult Coalition

	["PHYSICS"] = 34244459, -- PHYSICS Division
	["BD"] = 34202533, -- Broken Dagger
	["HRS"] = 35649470, -- Hellraisers

	-- Acting
	["AA"] = 34020767, -- Anomaly Actors
	["LD"] = 34603192, -- Lore Department

	-- Site Valora
	["SV"] = 509465666, -- Site Valora
	["SVSD"] = 242454114, -- Site Valora Security Department
	["SVMS"] = 1086950374, -- Site Valora Medical Support
	["SVRE"] = 317870759, -- Site Valora Research and Engineering

	-- Enforcement/legislative
	["AD"] = 35658983, -- Administrative Department
	["ACO"] = 35499260, -- Accountability and Corrections Office

	-- Other departments
	["SCD"] = 35500072, -- Scientific Department
	["SCD>SPEC"] = 140773662, -- ScD > Specializations

	["MD"] = 35385779, -- Medicinal Department
	["ETS"] = 35684607, -- Engineering and Technical Services
	["DEA"] = 35684604, -- Department of External Affairs

	-- Combatives
	["SC"] = 34030089, -- Security Corps

	-- SC Divisions
	["CIU"] = 35385764, -- Crisis Intervention Unit
	["OSS"] = 35385750, -- Operational Security Services
	["SRVCS"] = 812280736, -- OSS > Services
	["MP"] = 35385759, -- Military Police
	["HG"] = 296752941, -- Honor Guard

	-- Mobile Task Forces
	["MTFI"] = 35499281, -- Mesmyrize's Mobile Task Forces Initiative

	["1BN"] = 490963721, -- 1st Battalion (civils)

	-- MTF > Task Forces
	
	["O1"] = 1011557392, -- Omega-1
	["T1"] = 510494999, -- Titan-1
	["A9"] = 34993920, -- Alpha-9
	
	["I10"] = 96620365, -- Iota-10
	["E11"] = 34030102, -- Epsilon-11
	["N7"] = 786223936, -- Nu-7
	
	["A1"] = 373738150, -- Alpha-1
	["Z19"] = 238502777, -- Zeta-19
	["T5"] = 140615530, -- Tau-5
	["E9"] = 727953618, -- Epsilon-9
}