return {
	["Manufacturing Department"] = "MaD",
	["Anomaly Actors"] = "AA",
	["Lore Department"] = "LD",
	
	["Scientific Department"] = "ScD",
	["Medicinal Department"] = "MD",
	["Administrative Department"] = "AD",
	["Engineering and Technical Services"] = "ETS",
	["Department of External Affairs"] = "DEA",
	
	["Accountability and Corrections Office"] = "ACO",
	["Community Safety Office"] = "CSO",
	
	["Security Corps"] = "SC",
	
	["Mobile Task Forces"] = "MTF",
	["Anderson's Robotics"] = "AR",
	["Global Occult Coalition"] = "GOC",
}